### ISSUE TITLE
Unnecessary reference pass 

### ISSUE THREAD

**Issue by OroArmor** [AwpData/Impossible-GuessANumber#1]
https://github.com/AwpData/Impossible-GuessANumber/blob/493d4c9671d5017e656a747d83b4e6f1d623d995/ImpossibleGuessANumber/ImpossibleGuessANumber.cpp#L112

`int& guess` is passing a reference, when passing `int guess` does not. The reference isn't needed

**Comment by AwpData** [comment]
Thanks Eli, I’ll fix that
